language: node_js
node_js:
- '7'

cache:
  directories:
    - "${HOME}/.bower"
    - "${HOME}/.cache/bower"
  yarn: true

# https://yarnpkg.com/en/docs/install-ci#travis-tab
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --frozen-lockfile
  - (cd server && exec yarn install --frozen-lockfile)
  - (cd client && exec yarn install --frozen-lockfile)

before_script:
  - yarn global add gulp
  - yarn global add webpack

script:
  - (cd server && exec yarn run lint && exec yarn run test && exec yarn run build)
  - (cd client && exec yarn test)

after_success:
  - yarn run gulp

addons:
  artifacts:
    paths:
      - $(git ls-files -o test-results | tr "\n" ":")

deploy:
  provider: s3
  access_key_id: $ARTIFACTS_KEY
  secret_access_key: $ARTIFACTS_SECRET
  bucket: $ARTIFACTS_BUCKET
  region: $ARTIFACTS_REGION
  local_dir: dist
  upload-dir: $DIST_DIR
  skip_cleanup: true
  on:
    repo: trainline/environment-manager
    all_branches: true